### ISSUE TITLE
MUST NOT expose adminUsername as a parameter

### ISSUE THREAD

**Issue by AbelHu** [pivotal-cf/pcf-azure-arm-templates#2]
When I do not use the default name `ubuntu` as `adminUsername`, I cannot ssh to the OpsMan VM after deploying the template. But when I use the default name, I can. So it seems like that users cannot set the `adminUsername` to a different value.

**Comment by siennathesane** [comment]
Fixing this in #5, as you cannot change the username and get SSH-based access. The default is `ubuntu`, therefore it is hardcoded.
