### ISSUE TITLE
Do not need to specify the parameter storageEndpoint and location

### ISSUE THREAD

**Issue by bingosummer** [pivotal-cf/pcf-azure-arm-templates#3]
1. Using the function `reference`, you don't need to specify the parameter `storageEndpoint`.

    For example,
    https://github.com/Azure/azure-quickstart-templates/blob/0e5474f7e38cb51e6ca0d999d553cbbfabc65a84/bosh-setup/azuredeploy.json#L597

2. Using `resourceGroup().location`, you don't need to specify the parameter `location`. Then all resources will be created in the same location with the resource group location.

    For example,
    https://github.com/Azure/azure-quickstart-templates/blob/0e5474f7e38cb51e6ca0d999d553cbbfabc65a84/bosh-setup/azuredeploy.json#L616

**Comment by siennathesane** [comment]
Fixed in #5.
