### ISSUE TITLE
The deployment will fail if the location of the resource group is different from the location specified in `azure-deploy-parameters.json`

### ISSUE THREAD

**Issue by bingosummer** [pivotal-cf/pcf-azure-arm-templates#4]
If the location of the resource group is different from the location specified in `azure-deploy-parameters.json`, the deployment will fail because the load balancer and its public ip are in different locations.

https://github.com/pivotal-cf/pcf-azure-arm-templates/blob/master/azure-deploy.json#L281

**Comment by siennathesane** [comment]
Fixed in #5.
