### ISSUE TITLE
Create ERT-LB failed in deployment

### ISSUE THREAD

**Issue by weiil** [pivotal-cf/pcf-azure-arm-templates#6]
Hi,
I hit an error when deploy the latest template. 
On Azure portal, it indicates that create ERT-LB failed, cloud you please take a look.

-- Command 
az group deployment create --template-file azure-deploy.json --parameters azure-deploy-parameters.json --resource-group $RESOURCE_GROUP --name cfdeploy

-- Error message
Deployment failed. Correlation ID: 9e0066a0-c496-4163-8ddc-e803e9736bc2. {
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": []
  }
}

-- Parameters
{
  "parameters": {
    "BlobStorageContainer": {
      "value": "opsman-image"
    },
    "AdminSSHKey": {
      "value": "ssh-rsa ... ... ...YRZCiGPJS9 ubuntu"
    },
    "OpsManVHDStorageAccount": {
      "value": "mybosh4f2f9243"
    },
    "Location": {
      "value": "southeastasia"
    },
    "Environment": {
      "value": "AzureCloud"
    }
  },
  "contentVersion": "1.0.0.0",
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#"
}

-- Azure cli
 azure-xplat-cli v0.10.16
 azure-cli v2.0.19

Thanks!

**Comment by siennathesane** [comment]
@weiil thanks for this, I will take a look at it.

**Comment by siennathesane** [comment]
@weiil see #7
